name: production
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this 12:00 UTC every day
    - cron: '0 12 * * *'

  # Allow manually triggering of the workflow.
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  run-sdk-tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'node', 'php', 'python', 'ruby', 'dotnet', 'java' ]
    steps:
      - uses: actions/checkout@v3
      - name: run sdk tester
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LANGUAGE: ${{ matrix.language }}
          SERVER: 'api.hellosign.com'
        run: |
          ./build ${{ matrix.language }}
          pip install -U pytest
          pytest -svra  tests/

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

  notifiy-slack:
    needs: run-sdk-tester
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Post to a Slack channel
        id: slack-channel1
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # 'C030GQLB41L' for #alerts-eng-hs-api-notifications, 'C03U3TD1MA5' for #test-slackbot
          channel-id: 'C03U3TD1MA5'
          # For posting a simple plain text message
          slack-message: "Production SDK tester result: ${{ needs.run-sdk-tester.result }}\nLog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Post to a Slack channel
        id: slack-channel2
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # 'C030GQLB41L' for #alerts-eng-hs-api-notifications, 'C03U3TD1MA5' for #test-slackbot
          channel-id: 'C030GQLB41L'
          # For posting a simple plain text message
          slack-message: "Production SDK tester result: ${{ needs.run-sdk-tester.result }}\nLog: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
